server:
  port: 8001

spring:
  application:
    name: eureka-server-standalone
eureka:
  instance:
    hostname: localhost
    appname: eureka-server-standalone
  client:
    eurekaServiceUrlPollIntervalSeconds: 10
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false




